app = "testtracker"  # Replace this with your actual Fly.io app name

primary_region = "fra"

[env]
PORT = "3000"
LOG_PATH = "/data/visits.log" # for persistent volume (optional)

[[mounts]]
source = "data"
destination = "/data"
